"""Generate a Markdown skills index from the live registry.

This is the "self-updating docs" half of the router: it turns whatever
:func:`~skill_router.router.discover_skills` finds on disk into a grouped
Markdown table, so the human-facing index can never drift from the skills that
actually exist. It writes ``.claude/skills/INDEX.md`` rather than rewriting the
hand-authored ``README.md`` prose, so regeneration is always safe to re-run.
"""

from __future__ import annotations

from pathlib import Path

from .router import DEFAULT_SKILLS_DIR, Skill, discover_skills

_GENERATED_NOTE = (
    "<!-- Generated by `python -m skill_router --index`. Do not edit by hand; "
    "rerun to refresh. -->"
)


def _group_by_category(skills: list[Skill]) -> dict[str, list[Skill]]:
    grouped: dict[str, list[Skill]] = {}
    for skill in skills:
        grouped.setdefault(skill.category, []).append(skill)
    for bucket in grouped.values():
        bucket.sort(key=lambda s: s.name)
    return dict(sorted(grouped.items()))


def _escape(cell: str) -> str:
    """Keep pipe characters from breaking the Markdown table."""
    return cell.replace("|", "\\|").strip()


def build_index(skills_dir: Path | str = DEFAULT_SKILLS_DIR) -> str:
    """Return the full Markdown for an auto-generated skills index."""
    skills = discover_skills(skills_dir)
    grouped = _group_by_category(skills)

    lines: list[str] = [
        "# Skills index (auto-generated)",
        "",
        _GENERATED_NOTE,
        "",
        f"**{len(skills)}** skills registered across **{len(grouped)}** "
        "categories. Type `/<skill-name>` or just describe the task.",
        "",
    ]

    for category, bucket in grouped.items():
        lines.append(f"## {category}")
        lines.append("")
        lines.append("| Skill | What it does | Triggers |")
        lines.append("|---|---|---|")
        for skill in bucket:
            triggers = "; ".join(f'"{t}"' for t in skill.triggers[:3])
            lines.append(
                f"| `/{_escape(skill.name)}` "
                f"| {_escape(skill.summary) or '—'} "
                f"| {_escape(triggers) or '—'} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_index(
    skills_dir: Path | str = DEFAULT_SKILLS_DIR,
    out_path: Path | str | None = None,
) -> Path:
    """Write the generated index to ``INDEX.md`` and return its path."""
    target = Path(out_path) if out_path else Path(skills_dir) / "INDEX.md"
    target.write_text(build_index(skills_dir), encoding="utf-8")
    return target
